Add liquibase-maven-plugin and fixture-db
- fixture-db will be a publicly-accessible database for BMS external
users. Potentially it can be used to centralize some automated testing
that currently depends on DBScripts and other repos.
- Bump liquibase to 3.6.1 to fix liquibase issue CORE-2992:
liquibase.util.grammar.TokenMgrError: Lexical error

Issue: IBP-3221
Reviewer: None